name: Test
on:
  push:
    branches:
  pull_request:
  schedule:
    - cron: '11 1 * * 1'

jobs:
   test:
    uses: carlduevel/asdf-plugin-build-harness/.github/workflows/build.yml@master
    with:
      command: tfenv
